 // Sample temple data
 const temples = [
  {
    id: 1,
    name: "Guruvayoor Temple",
    location: "New Delhi, India",
    category: "Vishnu",
    region: "North Indian",
    image: "/temple-images/Neendoor.jpeg",
    hours: "5:00 AM - 9:00 PM",
    rating: 4.7,
    reviews: 231,
    distance: "2.5 km",
    favorite: true,
    featured: true,
    specialEvent: "Janmashtami celebrations",
    amenities: ["Parking", "Food", "Accommodation"],
  },
  {
    id: 2,
    name: "Meenakshi Temple",
    location: "Madurai, Tamil Nadu",
    category: "Shakti",
    region: "South Indian",
    image: "/temple-images/Neendoor.jpeg",
    hours: "5:00 AM - 10:00 PM",
    rating: 4.9,
    reviews: 412,
    distance: "450 km",
    favorite: true,
    featured: true,
    amenities: ["Parking", "Food", "Guides"],
  },
  {
    id: 3,
    name: "Kashi Vishwanath",
    location: "Varanasi, Uttar Pradesh",
    category: "Shiva",
    region: "North Indian",
    image: "/temple-images/Neendoor.jpeg",
    hours: "3:00 AM - 11:00 PM",
    rating: 4.8,
    reviews: 350,
    distance: "320 km",
    favorite: true,
    specialEvent: "Maha Shivaratri",
    amenities: ["Parking", "Accommodation", "River Access"],
  },
  {
    id: 4,
    name: "Tirupati Balaji",
    location: "Tirupati, Andhra Pradesh",
    category: "Vishnu",
    region: "South Indian",
    image: "/temple-images/Neendoor.jpeg",
    hours: "3:00 AM - 10:00 PM",
    rating: 5.0,
    reviews: 520,
    distance: "560 km",
    favorite: true,
    amenities: ["Parking", "Food", "Accommodation", "Shuttle"],
  },
  {
    id: 5,
    name: "Somnath Temple",
    location: "Somnath, Gujarat",
    category: "Shiva",
    region: "North Indian",
    image: "somnath.jpg",
    hours: "6:00 AM - 9:00 PM",
    rating: 4.6,
    reviews: 189,
    distance: "720 km",
    favorite: false,
    amenities: ["Parking", "Food", "Beach Access"],
  },
  {
    id: 6,
    name: "Golden Temple",
    location: "Amritsar, Punjab",
    category: "Sikh",
    region: "North Indian",
    image: "golden.jpg",
    hours: "24 hours",
    rating: 4.9,
    reviews: 480,
    distance: "430 km",
    favorite: false,
    featured: true,
    amenities: ["Parking", "Food", "Accommodation", "Lake"],
  },
  {
    id: 7,
    name: "Jagannath Temple",
    location: "Puri, Odisha",
    category: "Vishnu",
    region: "East Indian",
    image: "jagannath.jpg",
    hours: "5:00 AM - 10:00 PM",
    rating: 4.8,
    reviews: 275,
    distance: "850 km",
    favorite: false,
    specialEvent: "Rath Yatra festival",
    amenities: ["Parking", "Food", "Beach Access"],
  },
  {
    id: 8,
    name: "Badrinath Temple",
    location: "Badrinath, Uttarakhand",
    category: "Vishnu",
    region: "North Indian",
    image: "badrinath.jpg",
    hours: "6:00 AM - 8:30 PM",
    rating: 4.7,
    reviews: 210,
    distance: "950 km",
    favorite: false,
    amenities: ["Parking", "Food", "Mountain Views"],
  },
  {
    id: 9,
    name: "Siddhivinayak Temple",
    location: "Mumbai, Maharashtra",
    category: "Ganesh",
    region: "West Indian",
    image: "siddhivinayak.jpg",
    hours: "5:30 AM - 10:00 PM",
    rating: 4.5,
    reviews: 320,
    distance: "400 km",
    favorite: false,
    amenities: ["Parking", "Food"],
  },
];

export default temples;